language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
addons:
  apt:
    packages:
      - g++-multilib
      - scons
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons; fi
script:
  - ./build
  - ./test
