language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
addons:
  apt:
    packages:
      - g++-multilib
      - scons
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install scons; fi
script:
  - ./build
  - ./test
